name: C/C++ CI docker

on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          image: arm64v8/ubuntu:24.04
          label: arm64
        - os: ubuntu-latest
          image: balenalib/raspberry-pi
          label: armv6l
        - os: ubuntu-latest
          image: balenalib/raspberry-pi2
          label: armv7
        - os: ubuntu-latest
          image: ubuntu:24.04
          label: amd64

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Build an image from Dockerfile
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker build -t docker.io/${{ github.repository }}:${{ matrix.label }} --build-arg IMAGE=${{ matrix.image }} .
